# Generated by Django 3.1 on 2020-08-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogs_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='body',
            field=models.TextField(default='xyz'),
            preserve_default=False,
        ),
    ]
