# Generated by Django 3.1 on 2020-08-17 20:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogs_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
