# Generated by Django 3.1 on 2020-09-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20200819_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.TextField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='upvotes',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='liked',
            field=models.ManyToManyField(blank=True, editable=False, to='blogs.IP_Address'),
        ),
    ]
